# Motor Configuration for Drive Mechanics Package
# ROS2 Parameter format - all parameters must be under ros__parameters

drive_mechanics_node:
  ros__parameters:
    # Physical Robot Parameters
    robot:
      wheel_separation: 0.089 # Distance between drive wheel centers in meters (89mm)

    # Motor Control Parameters
    motor_control:
      max_speed: 0.8 # Increased from 0.6 for more responsive movement

    # Safety Parameters
    safety:
      max_linear_velocity: 0.5 # Increased from 0.3 for better response
      max_angular_velocity: 3.0 # Increased from 2.0 for better turning

    # Debugging and Development
    debug:
      enable_debug_output: false # Enable verbose debug messages
      test_mode: false # Enable test mode (safe for development)
